apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wiki-chart.fullname" . }}-grafana-dashboard
  labels:
    grafana_dashboard: "1"
data:
  creation-dashboard.json: |
{{ toYaml .Values.grafana.dashboards.creationDashboard | indent 4 }}
