apiVersion: v1
kind: Service
metadata:
  name: {{ include "wiki-chart.fullname" . }}-fastapi
spec:
  type: ClusterIP
  selector:
    app: {{ include "wiki-chart.fullname" . }}-fastapi
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
